FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x wait-for-it.sh
RUN mkdir /pdf_data

EXPOSE 5001

# CMD ["python", "app.py"]
ENTRYPOINT [ "./wait-for-it.sh", "chromadb:8000", "--timeout=60", "--", "python", "app.py" ]